name: Build and Push Docker Images

on:
  push:
    branches:
      - test_dockerCICD  # Trigger workflow on push to main branch

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: dhammikamahendra
          password: myDOCKER123

      # Step 3: Build and Push Images for Each Service
      - name: Build and Push Images
        run: |
          # Define services and their Dockerfiles
          services=("APIgateway" "AuthService" "OrderService" "ProductService")
          registry="dhammikamahendra"

          for service in "${services[@]}"; do
            # Build the image
            docker build -t $registry/$service:latest -f $service/Dockerfile $service

            # Push the image to Docker Hub
            docker push $registry/$service:latest
          done
