name: Build and Push Docker Images

on:
  push:
    branches:
      - test_dockerCICD  # Trigger workflow on push to main branch

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up JDK for Java project (optional, if needed for your project)
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'  # You can also use 'adoptopenjdk' or 'zulu'

      # Step 3: Build the JAR using Maven (or Gradle if you're using that)
      - name: Build the JAR
        run: mvn clean package

      # Step 4: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: dhammikamahendra
          password: myDOCKER123

      # Step 5: Build and Push Images for Each Service
      - name: Build and Push Images
        run: |
          # Define services with their original names (case-sensitive)
          services=("APIgateway" "AuthService" "OrderService" "ProductService")
          registry=dhammikamahendra

          for service in "${services[@]}"; do
            # Convert service name to lowercase
            lowercase_service=$(echo "$service" | tr '[:upper:]' '[:lower:]')

            # Build the Docker image
            docker build -t $registry/$lowercase_service:latest -f $service/Dockerfile $service

            # Push the Docker image to Docker Hub
            docker push $registry/$lowercase_service:latest
          done
